// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

package com.microsoft.cellsar.protobuf;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscriberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.microsoft.cellsar.protobuf.Subscriber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string imsi = 1;</code>
     */
    java.lang.String getImsi();
    /**
     * <code>string imsi = 1;</code>
     */
    com.google.protobuf.ByteString
        getImsiBytes();

    /**
     * <code>string tmsi = 2;</code>
     */
    java.lang.String getTmsi();
    /**
     * <code>string tmsi = 2;</code>
     */
    com.google.protobuf.ByteString
        getTmsiBytes();

    /**
     * <code>string msisdn = 3;</code>
     */
    java.lang.String getMsisdn();
    /**
     * <code>string msisdn = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsisdnBytes();
  }
  /**
   * Protobuf type {@code com.microsoft.cellsar.protobuf.Subscriber}
   */
  public  static final class Subscriber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.microsoft.cellsar.protobuf.Subscriber)
      SubscriberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Subscriber.newBuilder() to construct.
    private Subscriber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Subscriber() {
      imsi_ = "";
      tmsi_ = "";
      msisdn_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Subscriber(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              imsi_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              tmsi_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              msisdn_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microsoft.cellsar.protobuf.Data.internal_static_com_microsoft_cellsar_protobuf_Subscriber_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microsoft.cellsar.protobuf.Data.internal_static_com_microsoft_cellsar_protobuf_Subscriber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microsoft.cellsar.protobuf.Data.Subscriber.class, com.microsoft.cellsar.protobuf.Data.Subscriber.Builder.class);
    }

    public static final int IMSI_FIELD_NUMBER = 1;
    private volatile java.lang.Object imsi_;
    /**
     * <code>string imsi = 1;</code>
     */
    public java.lang.String getImsi() {
      java.lang.Object ref = imsi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imsi_ = s;
        return s;
      }
    }
    /**
     * <code>string imsi = 1;</code>
     */
    public com.google.protobuf.ByteString
        getImsiBytes() {
      java.lang.Object ref = imsi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imsi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TMSI_FIELD_NUMBER = 2;
    private volatile java.lang.Object tmsi_;
    /**
     * <code>string tmsi = 2;</code>
     */
    public java.lang.String getTmsi() {
      java.lang.Object ref = tmsi_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tmsi_ = s;
        return s;
      }
    }
    /**
     * <code>string tmsi = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTmsiBytes() {
      java.lang.Object ref = tmsi_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tmsi_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSISDN_FIELD_NUMBER = 3;
    private volatile java.lang.Object msisdn_;
    /**
     * <code>string msisdn = 3;</code>
     */
    public java.lang.String getMsisdn() {
      java.lang.Object ref = msisdn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msisdn_ = s;
        return s;
      }
    }
    /**
     * <code>string msisdn = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsisdnBytes() {
      java.lang.Object ref = msisdn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msisdn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getImsiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, imsi_);
      }
      if (!getTmsiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tmsi_);
      }
      if (!getMsisdnBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msisdn_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getImsiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, imsi_);
      }
      if (!getTmsiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tmsi_);
      }
      if (!getMsisdnBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msisdn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microsoft.cellsar.protobuf.Data.Subscriber)) {
        return super.equals(obj);
      }
      com.microsoft.cellsar.protobuf.Data.Subscriber other = (com.microsoft.cellsar.protobuf.Data.Subscriber) obj;

      boolean result = true;
      result = result && getImsi()
          .equals(other.getImsi());
      result = result && getTmsi()
          .equals(other.getTmsi());
      result = result && getMsisdn()
          .equals(other.getMsisdn());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IMSI_FIELD_NUMBER;
      hash = (53 * hash) + getImsi().hashCode();
      hash = (37 * hash) + TMSI_FIELD_NUMBER;
      hash = (53 * hash) + getTmsi().hashCode();
      hash = (37 * hash) + MSISDN_FIELD_NUMBER;
      hash = (53 * hash) + getMsisdn().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.Data.Subscriber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microsoft.cellsar.protobuf.Data.Subscriber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.microsoft.cellsar.protobuf.Subscriber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.microsoft.cellsar.protobuf.Subscriber)
        com.microsoft.cellsar.protobuf.Data.SubscriberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microsoft.cellsar.protobuf.Data.internal_static_com_microsoft_cellsar_protobuf_Subscriber_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microsoft.cellsar.protobuf.Data.internal_static_com_microsoft_cellsar_protobuf_Subscriber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microsoft.cellsar.protobuf.Data.Subscriber.class, com.microsoft.cellsar.protobuf.Data.Subscriber.Builder.class);
      }

      // Construct using com.microsoft.cellsar.protobuf.Data.Subscriber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        imsi_ = "";

        tmsi_ = "";

        msisdn_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microsoft.cellsar.protobuf.Data.internal_static_com_microsoft_cellsar_protobuf_Subscriber_descriptor;
      }

      public com.microsoft.cellsar.protobuf.Data.Subscriber getDefaultInstanceForType() {
        return com.microsoft.cellsar.protobuf.Data.Subscriber.getDefaultInstance();
      }

      public com.microsoft.cellsar.protobuf.Data.Subscriber build() {
        com.microsoft.cellsar.protobuf.Data.Subscriber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.microsoft.cellsar.protobuf.Data.Subscriber buildPartial() {
        com.microsoft.cellsar.protobuf.Data.Subscriber result = new com.microsoft.cellsar.protobuf.Data.Subscriber(this);
        result.imsi_ = imsi_;
        result.tmsi_ = tmsi_;
        result.msisdn_ = msisdn_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microsoft.cellsar.protobuf.Data.Subscriber) {
          return mergeFrom((com.microsoft.cellsar.protobuf.Data.Subscriber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microsoft.cellsar.protobuf.Data.Subscriber other) {
        if (other == com.microsoft.cellsar.protobuf.Data.Subscriber.getDefaultInstance()) return this;
        if (!other.getImsi().isEmpty()) {
          imsi_ = other.imsi_;
          onChanged();
        }
        if (!other.getTmsi().isEmpty()) {
          tmsi_ = other.tmsi_;
          onChanged();
        }
        if (!other.getMsisdn().isEmpty()) {
          msisdn_ = other.msisdn_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.microsoft.cellsar.protobuf.Data.Subscriber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.microsoft.cellsar.protobuf.Data.Subscriber) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object imsi_ = "";
      /**
       * <code>string imsi = 1;</code>
       */
      public java.lang.String getImsi() {
        java.lang.Object ref = imsi_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          imsi_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string imsi = 1;</code>
       */
      public com.google.protobuf.ByteString
          getImsiBytes() {
        java.lang.Object ref = imsi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imsi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string imsi = 1;</code>
       */
      public Builder setImsi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imsi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string imsi = 1;</code>
       */
      public Builder clearImsi() {
        
        imsi_ = getDefaultInstance().getImsi();
        onChanged();
        return this;
      }
      /**
       * <code>string imsi = 1;</code>
       */
      public Builder setImsiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imsi_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tmsi_ = "";
      /**
       * <code>string tmsi = 2;</code>
       */
      public java.lang.String getTmsi() {
        java.lang.Object ref = tmsi_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tmsi_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string tmsi = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTmsiBytes() {
        java.lang.Object ref = tmsi_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tmsi_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tmsi = 2;</code>
       */
      public Builder setTmsi(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tmsi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tmsi = 2;</code>
       */
      public Builder clearTmsi() {
        
        tmsi_ = getDefaultInstance().getTmsi();
        onChanged();
        return this;
      }
      /**
       * <code>string tmsi = 2;</code>
       */
      public Builder setTmsiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tmsi_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msisdn_ = "";
      /**
       * <code>string msisdn = 3;</code>
       */
      public java.lang.String getMsisdn() {
        java.lang.Object ref = msisdn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msisdn_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msisdn = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsisdnBytes() {
        java.lang.Object ref = msisdn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msisdn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msisdn = 3;</code>
       */
      public Builder setMsisdn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msisdn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msisdn = 3;</code>
       */
      public Builder clearMsisdn() {
        
        msisdn_ = getDefaultInstance().getMsisdn();
        onChanged();
        return this;
      }
      /**
       * <code>string msisdn = 3;</code>
       */
      public Builder setMsisdnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msisdn_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.microsoft.cellsar.protobuf.Subscriber)
    }

    // @@protoc_insertion_point(class_scope:com.microsoft.cellsar.protobuf.Subscriber)
    private static final com.microsoft.cellsar.protobuf.Data.Subscriber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microsoft.cellsar.protobuf.Data.Subscriber();
    }

    public static com.microsoft.cellsar.protobuf.Data.Subscriber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscriber>
        PARSER = new com.google.protobuf.AbstractParser<Subscriber>() {
      public Subscriber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Subscriber(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Subscriber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscriber> getParserForType() {
      return PARSER;
    }

    public com.microsoft.cellsar.protobuf.Data.Subscriber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RadioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.microsoft.cellsar.protobuf.Radio)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool stopped = 1;</code>
     */
    boolean getStopped();

    /**
     * <code>string stopped_reason = 2;</code>
     */
    java.lang.String getStoppedReason();
    /**
     * <code>string stopped_reason = 2;</code>
     */
    com.google.protobuf.ByteString
        getStoppedReasonBytes();
  }
  /**
   * Protobuf type {@code com.microsoft.cellsar.protobuf.Radio}
   */
  public  static final class Radio extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.microsoft.cellsar.protobuf.Radio)
      RadioOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Radio.newBuilder() to construct.
    private Radio(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Radio() {
      stopped_ = false;
      stoppedReason_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Radio(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              stopped_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              stoppedReason_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microsoft.cellsar.protobuf.Data.internal_static_com_microsoft_cellsar_protobuf_Radio_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microsoft.cellsar.protobuf.Data.internal_static_com_microsoft_cellsar_protobuf_Radio_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microsoft.cellsar.protobuf.Data.Radio.class, com.microsoft.cellsar.protobuf.Data.Radio.Builder.class);
    }

    public static final int STOPPED_FIELD_NUMBER = 1;
    private boolean stopped_;
    /**
     * <code>bool stopped = 1;</code>
     */
    public boolean getStopped() {
      return stopped_;
    }

    public static final int STOPPED_REASON_FIELD_NUMBER = 2;
    private volatile java.lang.Object stoppedReason_;
    /**
     * <code>string stopped_reason = 2;</code>
     */
    public java.lang.String getStoppedReason() {
      java.lang.Object ref = stoppedReason_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stoppedReason_ = s;
        return s;
      }
    }
    /**
     * <code>string stopped_reason = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStoppedReasonBytes() {
      java.lang.Object ref = stoppedReason_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stoppedReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stopped_ != false) {
        output.writeBool(1, stopped_);
      }
      if (!getStoppedReasonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stoppedReason_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stopped_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, stopped_);
      }
      if (!getStoppedReasonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stoppedReason_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microsoft.cellsar.protobuf.Data.Radio)) {
        return super.equals(obj);
      }
      com.microsoft.cellsar.protobuf.Data.Radio other = (com.microsoft.cellsar.protobuf.Data.Radio) obj;

      boolean result = true;
      result = result && (getStopped()
          == other.getStopped());
      result = result && getStoppedReason()
          .equals(other.getStoppedReason());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STOPPED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getStopped());
      hash = (37 * hash) + STOPPED_REASON_FIELD_NUMBER;
      hash = (53 * hash) + getStoppedReason().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microsoft.cellsar.protobuf.Data.Radio parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.Data.Radio parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microsoft.cellsar.protobuf.Data.Radio prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.microsoft.cellsar.protobuf.Radio}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.microsoft.cellsar.protobuf.Radio)
        com.microsoft.cellsar.protobuf.Data.RadioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microsoft.cellsar.protobuf.Data.internal_static_com_microsoft_cellsar_protobuf_Radio_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microsoft.cellsar.protobuf.Data.internal_static_com_microsoft_cellsar_protobuf_Radio_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microsoft.cellsar.protobuf.Data.Radio.class, com.microsoft.cellsar.protobuf.Data.Radio.Builder.class);
      }

      // Construct using com.microsoft.cellsar.protobuf.Data.Radio.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        stopped_ = false;

        stoppedReason_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microsoft.cellsar.protobuf.Data.internal_static_com_microsoft_cellsar_protobuf_Radio_descriptor;
      }

      public com.microsoft.cellsar.protobuf.Data.Radio getDefaultInstanceForType() {
        return com.microsoft.cellsar.protobuf.Data.Radio.getDefaultInstance();
      }

      public com.microsoft.cellsar.protobuf.Data.Radio build() {
        com.microsoft.cellsar.protobuf.Data.Radio result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.microsoft.cellsar.protobuf.Data.Radio buildPartial() {
        com.microsoft.cellsar.protobuf.Data.Radio result = new com.microsoft.cellsar.protobuf.Data.Radio(this);
        result.stopped_ = stopped_;
        result.stoppedReason_ = stoppedReason_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microsoft.cellsar.protobuf.Data.Radio) {
          return mergeFrom((com.microsoft.cellsar.protobuf.Data.Radio)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microsoft.cellsar.protobuf.Data.Radio other) {
        if (other == com.microsoft.cellsar.protobuf.Data.Radio.getDefaultInstance()) return this;
        if (other.getStopped() != false) {
          setStopped(other.getStopped());
        }
        if (!other.getStoppedReason().isEmpty()) {
          stoppedReason_ = other.stoppedReason_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.microsoft.cellsar.protobuf.Data.Radio parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.microsoft.cellsar.protobuf.Data.Radio) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean stopped_ ;
      /**
       * <code>bool stopped = 1;</code>
       */
      public boolean getStopped() {
        return stopped_;
      }
      /**
       * <code>bool stopped = 1;</code>
       */
      public Builder setStopped(boolean value) {
        
        stopped_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool stopped = 1;</code>
       */
      public Builder clearStopped() {
        
        stopped_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object stoppedReason_ = "";
      /**
       * <code>string stopped_reason = 2;</code>
       */
      public java.lang.String getStoppedReason() {
        java.lang.Object ref = stoppedReason_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stoppedReason_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stopped_reason = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStoppedReasonBytes() {
        java.lang.Object ref = stoppedReason_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stoppedReason_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stopped_reason = 2;</code>
       */
      public Builder setStoppedReason(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stoppedReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stopped_reason = 2;</code>
       */
      public Builder clearStoppedReason() {
        
        stoppedReason_ = getDefaultInstance().getStoppedReason();
        onChanged();
        return this;
      }
      /**
       * <code>string stopped_reason = 2;</code>
       */
      public Builder setStoppedReasonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stoppedReason_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.microsoft.cellsar.protobuf.Radio)
    }

    // @@protoc_insertion_point(class_scope:com.microsoft.cellsar.protobuf.Radio)
    private static final com.microsoft.cellsar.protobuf.Data.Radio DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microsoft.cellsar.protobuf.Data.Radio();
    }

    public static com.microsoft.cellsar.protobuf.Data.Radio getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Radio>
        PARSER = new com.google.protobuf.AbstractParser<Radio>() {
      public Radio parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Radio(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Radio> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Radio> getParserForType() {
      return PARSER;
    }

    public com.microsoft.cellsar.protobuf.Data.Radio getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_microsoft_cellsar_protobuf_Subscriber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_microsoft_cellsar_protobuf_Subscriber_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_microsoft_cellsar_protobuf_Radio_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_microsoft_cellsar_protobuf_Radio_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndata.proto\022\036com.microsoft.cellsar.prot" +
      "obuf\"8\n\nSubscriber\022\014\n\004imsi\030\001 \001(\t\022\014\n\004tmsi" +
      "\030\002 \001(\t\022\016\n\006msisdn\030\003 \001(\t\"0\n\005Radio\022\017\n\007stopp" +
      "ed\030\001 \001(\010\022\026\n\016stopped_reason\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_microsoft_cellsar_protobuf_Subscriber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_microsoft_cellsar_protobuf_Subscriber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_microsoft_cellsar_protobuf_Subscriber_descriptor,
        new java.lang.String[] { "Imsi", "Tmsi", "Msisdn", });
    internal_static_com_microsoft_cellsar_protobuf_Radio_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_microsoft_cellsar_protobuf_Radio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_microsoft_cellsar_protobuf_Radio_descriptor,
        new java.lang.String[] { "Stopped", "StoppedReason", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
