// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: from_fc.proto

package com.microsoft.cellsar.protobuf.fc;

public final class FromFc {
  private FromFc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlmnDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.microsoft.cellsar.protobuf.fc.PlmnData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mcc = 1;</code>
     */
    java.lang.String getMcc();
    /**
     * <code>string mcc = 1;</code>
     */
    com.google.protobuf.ByteString
        getMccBytes();

    /**
     * <code>string mnc = 2;</code>
     */
    java.lang.String getMnc();
    /**
     * <code>string mnc = 2;</code>
     */
    com.google.protobuf.ByteString
        getMncBytes();
  }
  /**
   * Protobuf type {@code com.microsoft.cellsar.protobuf.fc.PlmnData}
   */
  public  static final class PlmnData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.microsoft.cellsar.protobuf.fc.PlmnData)
      PlmnDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlmnData.newBuilder() to construct.
    private PlmnData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlmnData() {
      mcc_ = "";
      mnc_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlmnData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mcc_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              mnc_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_PlmnData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_PlmnData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.class, com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.Builder.class);
    }

    public static final int MCC_FIELD_NUMBER = 1;
    private volatile java.lang.Object mcc_;
    /**
     * <code>string mcc = 1;</code>
     */
    public java.lang.String getMcc() {
      java.lang.Object ref = mcc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mcc_ = s;
        return s;
      }
    }
    /**
     * <code>string mcc = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMccBytes() {
      java.lang.Object ref = mcc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mcc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MNC_FIELD_NUMBER = 2;
    private volatile java.lang.Object mnc_;
    /**
     * <code>string mnc = 2;</code>
     */
    public java.lang.String getMnc() {
      java.lang.Object ref = mnc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mnc_ = s;
        return s;
      }
    }
    /**
     * <code>string mnc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMncBytes() {
      java.lang.Object ref = mnc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mnc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMccBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mcc_);
      }
      if (!getMncBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mnc_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMccBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mcc_);
      }
      if (!getMncBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mnc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData)) {
        return super.equals(obj);
      }
      com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData other = (com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData) obj;

      boolean result = true;
      result = result && getMcc()
          .equals(other.getMcc());
      result = result && getMnc()
          .equals(other.getMnc());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MCC_FIELD_NUMBER;
      hash = (53 * hash) + getMcc().hashCode();
      hash = (37 * hash) + MNC_FIELD_NUMBER;
      hash = (53 * hash) + getMnc().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.microsoft.cellsar.protobuf.fc.PlmnData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.microsoft.cellsar.protobuf.fc.PlmnData)
        com.microsoft.cellsar.protobuf.fc.FromFc.PlmnDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_PlmnData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_PlmnData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.class, com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.Builder.class);
      }

      // Construct using com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        mcc_ = "";

        mnc_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_PlmnData_descriptor;
      }

      public com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData getDefaultInstanceForType() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.getDefaultInstance();
      }

      public com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData build() {
        com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData buildPartial() {
        com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData result = new com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData(this);
        result.mcc_ = mcc_;
        result.mnc_ = mnc_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData) {
          return mergeFrom((com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData other) {
        if (other == com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.getDefaultInstance()) return this;
        if (!other.getMcc().isEmpty()) {
          mcc_ = other.mcc_;
          onChanged();
        }
        if (!other.getMnc().isEmpty()) {
          mnc_ = other.mnc_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object mcc_ = "";
      /**
       * <code>string mcc = 1;</code>
       */
      public java.lang.String getMcc() {
        java.lang.Object ref = mcc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mcc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mcc = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMccBytes() {
        java.lang.Object ref = mcc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mcc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mcc = 1;</code>
       */
      public Builder setMcc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mcc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mcc = 1;</code>
       */
      public Builder clearMcc() {
        
        mcc_ = getDefaultInstance().getMcc();
        onChanged();
        return this;
      }
      /**
       * <code>string mcc = 1;</code>
       */
      public Builder setMccBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mcc_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mnc_ = "";
      /**
       * <code>string mnc = 2;</code>
       */
      public java.lang.String getMnc() {
        java.lang.Object ref = mnc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mnc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mnc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMncBytes() {
        java.lang.Object ref = mnc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mnc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mnc = 2;</code>
       */
      public Builder setMnc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mnc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mnc = 2;</code>
       */
      public Builder clearMnc() {
        
        mnc_ = getDefaultInstance().getMnc();
        onChanged();
        return this;
      }
      /**
       * <code>string mnc = 2;</code>
       */
      public Builder setMncBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mnc_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.microsoft.cellsar.protobuf.fc.PlmnData)
    }

    // @@protoc_insertion_point(class_scope:com.microsoft.cellsar.protobuf.fc.PlmnData)
    private static final com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData();
    }

    public static com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlmnData>
        PARSER = new com.google.protobuf.AbstractParser<PlmnData>() {
      public PlmnData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlmnData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlmnData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlmnData> getParserForType() {
      return PARSER;
    }

    public com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SmsDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.microsoft.cellsar.protobuf.fc.SmsData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
     */
    boolean hasSubscriber();
    /**
     * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
     */
    com.microsoft.cellsar.protobuf.Data.Subscriber getSubscriber();
    /**
     * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
     */
    com.microsoft.cellsar.protobuf.Data.SubscriberOrBuilder getSubscriberOrBuilder();

    /**
     * <code>string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>uint32 tries = 3;</code>
     */
    int getTries();
  }
  /**
   * Protobuf type {@code com.microsoft.cellsar.protobuf.fc.SmsData}
   */
  public  static final class SmsData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.microsoft.cellsar.protobuf.fc.SmsData)
      SmsDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SmsData.newBuilder() to construct.
    private SmsData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SmsData() {
      msg_ = "";
      tries_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SmsData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.microsoft.cellsar.protobuf.Data.Subscriber.Builder subBuilder = null;
              if (subscriber_ != null) {
                subBuilder = subscriber_.toBuilder();
              }
              subscriber_ = input.readMessage(com.microsoft.cellsar.protobuf.Data.Subscriber.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(subscriber_);
                subscriber_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 24: {

              tries_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_SmsData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_SmsData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.class, com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.Builder.class);
    }

    public static final int SUBSCRIBER_FIELD_NUMBER = 1;
    private com.microsoft.cellsar.protobuf.Data.Subscriber subscriber_;
    /**
     * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
     */
    public boolean hasSubscriber() {
      return subscriber_ != null;
    }
    /**
     * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
     */
    public com.microsoft.cellsar.protobuf.Data.Subscriber getSubscriber() {
      return subscriber_ == null ? com.microsoft.cellsar.protobuf.Data.Subscriber.getDefaultInstance() : subscriber_;
    }
    /**
     * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
     */
    public com.microsoft.cellsar.protobuf.Data.SubscriberOrBuilder getSubscriberOrBuilder() {
      return getSubscriber();
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIES_FIELD_NUMBER = 3;
    private int tries_;
    /**
     * <code>uint32 tries = 3;</code>
     */
    public int getTries() {
      return tries_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (subscriber_ != null) {
        output.writeMessage(1, getSubscriber());
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (tries_ != 0) {
        output.writeUInt32(3, tries_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (subscriber_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSubscriber());
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (tries_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, tries_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microsoft.cellsar.protobuf.fc.FromFc.SmsData)) {
        return super.equals(obj);
      }
      com.microsoft.cellsar.protobuf.fc.FromFc.SmsData other = (com.microsoft.cellsar.protobuf.fc.FromFc.SmsData) obj;

      boolean result = true;
      result = result && (hasSubscriber() == other.hasSubscriber());
      if (hasSubscriber()) {
        result = result && getSubscriber()
            .equals(other.getSubscriber());
      }
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (getTries()
          == other.getTries());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSubscriber()) {
        hash = (37 * hash) + SUBSCRIBER_FIELD_NUMBER;
        hash = (53 * hash) + getSubscriber().hashCode();
      }
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + TRIES_FIELD_NUMBER;
      hash = (53 * hash) + getTries();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microsoft.cellsar.protobuf.fc.FromFc.SmsData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.microsoft.cellsar.protobuf.fc.SmsData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.microsoft.cellsar.protobuf.fc.SmsData)
        com.microsoft.cellsar.protobuf.fc.FromFc.SmsDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_SmsData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_SmsData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.class, com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.Builder.class);
      }

      // Construct using com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (subscriberBuilder_ == null) {
          subscriber_ = null;
        } else {
          subscriber_ = null;
          subscriberBuilder_ = null;
        }
        msg_ = "";

        tries_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_SmsData_descriptor;
      }

      public com.microsoft.cellsar.protobuf.fc.FromFc.SmsData getDefaultInstanceForType() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.getDefaultInstance();
      }

      public com.microsoft.cellsar.protobuf.fc.FromFc.SmsData build() {
        com.microsoft.cellsar.protobuf.fc.FromFc.SmsData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.microsoft.cellsar.protobuf.fc.FromFc.SmsData buildPartial() {
        com.microsoft.cellsar.protobuf.fc.FromFc.SmsData result = new com.microsoft.cellsar.protobuf.fc.FromFc.SmsData(this);
        if (subscriberBuilder_ == null) {
          result.subscriber_ = subscriber_;
        } else {
          result.subscriber_ = subscriberBuilder_.build();
        }
        result.msg_ = msg_;
        result.tries_ = tries_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microsoft.cellsar.protobuf.fc.FromFc.SmsData) {
          return mergeFrom((com.microsoft.cellsar.protobuf.fc.FromFc.SmsData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microsoft.cellsar.protobuf.fc.FromFc.SmsData other) {
        if (other == com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.getDefaultInstance()) return this;
        if (other.hasSubscriber()) {
          mergeSubscriber(other.getSubscriber());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getTries() != 0) {
          setTries(other.getTries());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.microsoft.cellsar.protobuf.fc.FromFc.SmsData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.microsoft.cellsar.protobuf.fc.FromFc.SmsData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.microsoft.cellsar.protobuf.Data.Subscriber subscriber_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.microsoft.cellsar.protobuf.Data.Subscriber, com.microsoft.cellsar.protobuf.Data.Subscriber.Builder, com.microsoft.cellsar.protobuf.Data.SubscriberOrBuilder> subscriberBuilder_;
      /**
       * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
       */
      public boolean hasSubscriber() {
        return subscriberBuilder_ != null || subscriber_ != null;
      }
      /**
       * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
       */
      public com.microsoft.cellsar.protobuf.Data.Subscriber getSubscriber() {
        if (subscriberBuilder_ == null) {
          return subscriber_ == null ? com.microsoft.cellsar.protobuf.Data.Subscriber.getDefaultInstance() : subscriber_;
        } else {
          return subscriberBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
       */
      public Builder setSubscriber(com.microsoft.cellsar.protobuf.Data.Subscriber value) {
        if (subscriberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subscriber_ = value;
          onChanged();
        } else {
          subscriberBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
       */
      public Builder setSubscriber(
          com.microsoft.cellsar.protobuf.Data.Subscriber.Builder builderForValue) {
        if (subscriberBuilder_ == null) {
          subscriber_ = builderForValue.build();
          onChanged();
        } else {
          subscriberBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
       */
      public Builder mergeSubscriber(com.microsoft.cellsar.protobuf.Data.Subscriber value) {
        if (subscriberBuilder_ == null) {
          if (subscriber_ != null) {
            subscriber_ =
              com.microsoft.cellsar.protobuf.Data.Subscriber.newBuilder(subscriber_).mergeFrom(value).buildPartial();
          } else {
            subscriber_ = value;
          }
          onChanged();
        } else {
          subscriberBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
       */
      public Builder clearSubscriber() {
        if (subscriberBuilder_ == null) {
          subscriber_ = null;
          onChanged();
        } else {
          subscriber_ = null;
          subscriberBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
       */
      public com.microsoft.cellsar.protobuf.Data.Subscriber.Builder getSubscriberBuilder() {
        
        onChanged();
        return getSubscriberFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
       */
      public com.microsoft.cellsar.protobuf.Data.SubscriberOrBuilder getSubscriberOrBuilder() {
        if (subscriberBuilder_ != null) {
          return subscriberBuilder_.getMessageOrBuilder();
        } else {
          return subscriber_ == null ?
              com.microsoft.cellsar.protobuf.Data.Subscriber.getDefaultInstance() : subscriber_;
        }
      }
      /**
       * <code>.com.microsoft.cellsar.protobuf.Subscriber subscriber = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.microsoft.cellsar.protobuf.Data.Subscriber, com.microsoft.cellsar.protobuf.Data.Subscriber.Builder, com.microsoft.cellsar.protobuf.Data.SubscriberOrBuilder> 
          getSubscriberFieldBuilder() {
        if (subscriberBuilder_ == null) {
          subscriberBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.microsoft.cellsar.protobuf.Data.Subscriber, com.microsoft.cellsar.protobuf.Data.Subscriber.Builder, com.microsoft.cellsar.protobuf.Data.SubscriberOrBuilder>(
                  getSubscriber(),
                  getParentForChildren(),
                  isClean());
          subscriber_ = null;
        }
        return subscriberBuilder_;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private int tries_ ;
      /**
       * <code>uint32 tries = 3;</code>
       */
      public int getTries() {
        return tries_;
      }
      /**
       * <code>uint32 tries = 3;</code>
       */
      public Builder setTries(int value) {
        
        tries_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 tries = 3;</code>
       */
      public Builder clearTries() {
        
        tries_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.microsoft.cellsar.protobuf.fc.SmsData)
    }

    // @@protoc_insertion_point(class_scope:com.microsoft.cellsar.protobuf.fc.SmsData)
    private static final com.microsoft.cellsar.protobuf.fc.FromFc.SmsData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microsoft.cellsar.protobuf.fc.FromFc.SmsData();
    }

    public static com.microsoft.cellsar.protobuf.fc.FromFc.SmsData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SmsData>
        PARSER = new com.google.protobuf.AbstractParser<SmsData>() {
      public SmsData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SmsData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SmsData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SmsData> getParserForType() {
      return PARSER;
    }

    public com.microsoft.cellsar.protobuf.fc.FromFc.SmsData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FcMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.microsoft.cellsar.protobuf.fc.FcMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>uint64 time = 2;</code>
     */
    long getTime();

    /**
     * <pre>
     * One of these types will be used, depending on 'type'
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
     */
    boolean hasPlmnData();
    /**
     * <pre>
     * One of these types will be used, depending on 'type'
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
     */
    com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData getPlmnData();
    /**
     * <pre>
     * One of these types will be used, depending on 'type'
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
     */
    com.microsoft.cellsar.protobuf.fc.FromFc.PlmnDataOrBuilder getPlmnDataOrBuilder();

    /**
     * <pre>
     * type == "sms"
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
     */
    boolean hasSmsData();
    /**
     * <pre>
     * type == "sms"
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
     */
    com.microsoft.cellsar.protobuf.fc.FromFc.SmsData getSmsData();
    /**
     * <pre>
     * type == "sms"
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
     */
    com.microsoft.cellsar.protobuf.fc.FromFc.SmsDataOrBuilder getSmsDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.microsoft.cellsar.protobuf.fc.FcMessage}
   */
  public  static final class FcMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.microsoft.cellsar.protobuf.fc.FcMessage)
      FcMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FcMessage.newBuilder() to construct.
    private FcMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FcMessage() {
      type_ = "";
      time_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FcMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 16: {

              time_ = input.readUInt64();
              break;
            }
            case 26: {
              com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.Builder subBuilder = null;
              if (plmnData_ != null) {
                subBuilder = plmnData_.toBuilder();
              }
              plmnData_ = input.readMessage(com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(plmnData_);
                plmnData_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.Builder subBuilder = null;
              if (smsData_ != null) {
                subBuilder = smsData_.toBuilder();
              }
              smsData_ = input.readMessage(com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(smsData_);
                smsData_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_FcMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_FcMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage.class, com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    /**
     * <code>uint64 time = 2;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int PLMN_DATA_FIELD_NUMBER = 3;
    private com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData plmnData_;
    /**
     * <pre>
     * One of these types will be used, depending on 'type'
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
     */
    public boolean hasPlmnData() {
      return plmnData_ != null;
    }
    /**
     * <pre>
     * One of these types will be used, depending on 'type'
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
     */
    public com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData getPlmnData() {
      return plmnData_ == null ? com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.getDefaultInstance() : plmnData_;
    }
    /**
     * <pre>
     * One of these types will be used, depending on 'type'
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
     */
    public com.microsoft.cellsar.protobuf.fc.FromFc.PlmnDataOrBuilder getPlmnDataOrBuilder() {
      return getPlmnData();
    }

    public static final int SMS_DATA_FIELD_NUMBER = 4;
    private com.microsoft.cellsar.protobuf.fc.FromFc.SmsData smsData_;
    /**
     * <pre>
     * type == "sms"
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
     */
    public boolean hasSmsData() {
      return smsData_ != null;
    }
    /**
     * <pre>
     * type == "sms"
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
     */
    public com.microsoft.cellsar.protobuf.fc.FromFc.SmsData getSmsData() {
      return smsData_ == null ? com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.getDefaultInstance() : smsData_;
    }
    /**
     * <pre>
     * type == "sms"
     * </pre>
     *
     * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
     */
    public com.microsoft.cellsar.protobuf.fc.FromFc.SmsDataOrBuilder getSmsDataOrBuilder() {
      return getSmsData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (time_ != 0L) {
        output.writeUInt64(2, time_);
      }
      if (plmnData_ != null) {
        output.writeMessage(3, getPlmnData());
      }
      if (smsData_ != null) {
        output.writeMessage(4, getSmsData());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, time_);
      }
      if (plmnData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPlmnData());
      }
      if (smsData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getSmsData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage)) {
        return super.equals(obj);
      }
      com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage other = (com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage) obj;

      boolean result = true;
      result = result && getType()
          .equals(other.getType());
      result = result && (getTime()
          == other.getTime());
      result = result && (hasPlmnData() == other.hasPlmnData());
      if (hasPlmnData()) {
        result = result && getPlmnData()
            .equals(other.getPlmnData());
      }
      result = result && (hasSmsData() == other.hasSmsData());
      if (hasSmsData()) {
        result = result && getSmsData()
            .equals(other.getSmsData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      if (hasPlmnData()) {
        hash = (37 * hash) + PLMN_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getPlmnData().hashCode();
      }
      if (hasSmsData()) {
        hash = (37 * hash) + SMS_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getSmsData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.microsoft.cellsar.protobuf.fc.FcMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.microsoft.cellsar.protobuf.fc.FcMessage)
        com.microsoft.cellsar.protobuf.fc.FromFc.FcMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_FcMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_FcMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage.class, com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage.Builder.class);
      }

      // Construct using com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = "";

        time_ = 0L;

        if (plmnDataBuilder_ == null) {
          plmnData_ = null;
        } else {
          plmnData_ = null;
          plmnDataBuilder_ = null;
        }
        if (smsDataBuilder_ == null) {
          smsData_ = null;
        } else {
          smsData_ = null;
          smsDataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.internal_static_com_microsoft_cellsar_protobuf_fc_FcMessage_descriptor;
      }

      public com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage getDefaultInstanceForType() {
        return com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage.getDefaultInstance();
      }

      public com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage build() {
        com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage buildPartial() {
        com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage result = new com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage(this);
        result.type_ = type_;
        result.time_ = time_;
        if (plmnDataBuilder_ == null) {
          result.plmnData_ = plmnData_;
        } else {
          result.plmnData_ = plmnDataBuilder_.build();
        }
        if (smsDataBuilder_ == null) {
          result.smsData_ = smsData_;
        } else {
          result.smsData_ = smsDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage) {
          return mergeFrom((com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage other) {
        if (other == com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.hasPlmnData()) {
          mergePlmnData(other.getPlmnData());
        }
        if (other.hasSmsData()) {
          mergeSmsData(other.getSmsData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>uint64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>uint64 time = 2;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 time = 2;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData plmnData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData, com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.Builder, com.microsoft.cellsar.protobuf.fc.FromFc.PlmnDataOrBuilder> plmnDataBuilder_;
      /**
       * <pre>
       * One of these types will be used, depending on 'type'
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
       */
      public boolean hasPlmnData() {
        return plmnDataBuilder_ != null || plmnData_ != null;
      }
      /**
       * <pre>
       * One of these types will be used, depending on 'type'
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
       */
      public com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData getPlmnData() {
        if (plmnDataBuilder_ == null) {
          return plmnData_ == null ? com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.getDefaultInstance() : plmnData_;
        } else {
          return plmnDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * One of these types will be used, depending on 'type'
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
       */
      public Builder setPlmnData(com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData value) {
        if (plmnDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          plmnData_ = value;
          onChanged();
        } else {
          plmnDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * One of these types will be used, depending on 'type'
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
       */
      public Builder setPlmnData(
          com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.Builder builderForValue) {
        if (plmnDataBuilder_ == null) {
          plmnData_ = builderForValue.build();
          onChanged();
        } else {
          plmnDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * One of these types will be used, depending on 'type'
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
       */
      public Builder mergePlmnData(com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData value) {
        if (plmnDataBuilder_ == null) {
          if (plmnData_ != null) {
            plmnData_ =
              com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.newBuilder(plmnData_).mergeFrom(value).buildPartial();
          } else {
            plmnData_ = value;
          }
          onChanged();
        } else {
          plmnDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * One of these types will be used, depending on 'type'
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
       */
      public Builder clearPlmnData() {
        if (plmnDataBuilder_ == null) {
          plmnData_ = null;
          onChanged();
        } else {
          plmnData_ = null;
          plmnDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * One of these types will be used, depending on 'type'
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
       */
      public com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.Builder getPlmnDataBuilder() {
        
        onChanged();
        return getPlmnDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * One of these types will be used, depending on 'type'
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
       */
      public com.microsoft.cellsar.protobuf.fc.FromFc.PlmnDataOrBuilder getPlmnDataOrBuilder() {
        if (plmnDataBuilder_ != null) {
          return plmnDataBuilder_.getMessageOrBuilder();
        } else {
          return plmnData_ == null ?
              com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.getDefaultInstance() : plmnData_;
        }
      }
      /**
       * <pre>
       * One of these types will be used, depending on 'type'
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.PlmnData plmn_data = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData, com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.Builder, com.microsoft.cellsar.protobuf.fc.FromFc.PlmnDataOrBuilder> 
          getPlmnDataFieldBuilder() {
        if (plmnDataBuilder_ == null) {
          plmnDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData, com.microsoft.cellsar.protobuf.fc.FromFc.PlmnData.Builder, com.microsoft.cellsar.protobuf.fc.FromFc.PlmnDataOrBuilder>(
                  getPlmnData(),
                  getParentForChildren(),
                  isClean());
          plmnData_ = null;
        }
        return plmnDataBuilder_;
      }

      private com.microsoft.cellsar.protobuf.fc.FromFc.SmsData smsData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.microsoft.cellsar.protobuf.fc.FromFc.SmsData, com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.Builder, com.microsoft.cellsar.protobuf.fc.FromFc.SmsDataOrBuilder> smsDataBuilder_;
      /**
       * <pre>
       * type == "sms"
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
       */
      public boolean hasSmsData() {
        return smsDataBuilder_ != null || smsData_ != null;
      }
      /**
       * <pre>
       * type == "sms"
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
       */
      public com.microsoft.cellsar.protobuf.fc.FromFc.SmsData getSmsData() {
        if (smsDataBuilder_ == null) {
          return smsData_ == null ? com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.getDefaultInstance() : smsData_;
        } else {
          return smsDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * type == "sms"
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
       */
      public Builder setSmsData(com.microsoft.cellsar.protobuf.fc.FromFc.SmsData value) {
        if (smsDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          smsData_ = value;
          onChanged();
        } else {
          smsDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * type == "sms"
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
       */
      public Builder setSmsData(
          com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.Builder builderForValue) {
        if (smsDataBuilder_ == null) {
          smsData_ = builderForValue.build();
          onChanged();
        } else {
          smsDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * type == "sms"
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
       */
      public Builder mergeSmsData(com.microsoft.cellsar.protobuf.fc.FromFc.SmsData value) {
        if (smsDataBuilder_ == null) {
          if (smsData_ != null) {
            smsData_ =
              com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.newBuilder(smsData_).mergeFrom(value).buildPartial();
          } else {
            smsData_ = value;
          }
          onChanged();
        } else {
          smsDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * type == "sms"
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
       */
      public Builder clearSmsData() {
        if (smsDataBuilder_ == null) {
          smsData_ = null;
          onChanged();
        } else {
          smsData_ = null;
          smsDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * type == "sms"
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
       */
      public com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.Builder getSmsDataBuilder() {
        
        onChanged();
        return getSmsDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * type == "sms"
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
       */
      public com.microsoft.cellsar.protobuf.fc.FromFc.SmsDataOrBuilder getSmsDataOrBuilder() {
        if (smsDataBuilder_ != null) {
          return smsDataBuilder_.getMessageOrBuilder();
        } else {
          return smsData_ == null ?
              com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.getDefaultInstance() : smsData_;
        }
      }
      /**
       * <pre>
       * type == "sms"
       * </pre>
       *
       * <code>.com.microsoft.cellsar.protobuf.fc.SmsData sms_data = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.microsoft.cellsar.protobuf.fc.FromFc.SmsData, com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.Builder, com.microsoft.cellsar.protobuf.fc.FromFc.SmsDataOrBuilder> 
          getSmsDataFieldBuilder() {
        if (smsDataBuilder_ == null) {
          smsDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.microsoft.cellsar.protobuf.fc.FromFc.SmsData, com.microsoft.cellsar.protobuf.fc.FromFc.SmsData.Builder, com.microsoft.cellsar.protobuf.fc.FromFc.SmsDataOrBuilder>(
                  getSmsData(),
                  getParentForChildren(),
                  isClean());
          smsData_ = null;
        }
        return smsDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.microsoft.cellsar.protobuf.fc.FcMessage)
    }

    // @@protoc_insertion_point(class_scope:com.microsoft.cellsar.protobuf.fc.FcMessage)
    private static final com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage();
    }

    public static com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FcMessage>
        PARSER = new com.google.protobuf.AbstractParser<FcMessage>() {
      public FcMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FcMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FcMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FcMessage> getParserForType() {
      return PARSER;
    }

    public com.microsoft.cellsar.protobuf.fc.FromFc.FcMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_microsoft_cellsar_protobuf_fc_PlmnData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_microsoft_cellsar_protobuf_fc_PlmnData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_microsoft_cellsar_protobuf_fc_SmsData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_microsoft_cellsar_protobuf_fc_SmsData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_microsoft_cellsar_protobuf_fc_FcMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_microsoft_cellsar_protobuf_fc_FcMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rfrom_fc.proto\022!com.microsoft.cellsar.p" +
      "rotobuf.fc\032\ndata.proto\"$\n\010PlmnData\022\013\n\003mc" +
      "c\030\001 \001(\t\022\013\n\003mnc\030\002 \001(\t\"e\n\007SmsData\022>\n\nsubsc" +
      "riber\030\001 \001(\0132*.com.microsoft.cellsar.prot" +
      "obuf.Subscriber\022\013\n\003msg\030\002 \001(\t\022\r\n\005tries\030\003 " +
      "\001(\r\"\245\001\n\tFcMessage\022\014\n\004type\030\001 \001(\t\022\014\n\004time\030" +
      "\002 \001(\004\022>\n\tplmn_data\030\003 \001(\0132+.com.microsoft" +
      ".cellsar.protobuf.fc.PlmnData\022<\n\010sms_dat" +
      "a\030\004 \001(\0132*.com.microsoft.cellsar.protobuf" +
      ".fc.SmsDatab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.microsoft.cellsar.protobuf.Data.getDescriptor(),
        }, assigner);
    internal_static_com_microsoft_cellsar_protobuf_fc_PlmnData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_microsoft_cellsar_protobuf_fc_PlmnData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_microsoft_cellsar_protobuf_fc_PlmnData_descriptor,
        new java.lang.String[] { "Mcc", "Mnc", });
    internal_static_com_microsoft_cellsar_protobuf_fc_SmsData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_microsoft_cellsar_protobuf_fc_SmsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_microsoft_cellsar_protobuf_fc_SmsData_descriptor,
        new java.lang.String[] { "Subscriber", "Msg", "Tries", });
    internal_static_com_microsoft_cellsar_protobuf_fc_FcMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_microsoft_cellsar_protobuf_fc_FcMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_microsoft_cellsar_protobuf_fc_FcMessage_descriptor,
        new java.lang.String[] { "Type", "Time", "PlmnData", "SmsData", });
    com.microsoft.cellsar.protobuf.Data.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
